### ISSUE TITLE
if ssh exc  `date +"%Y%m%d-%H%M%S"`

### ISSUE THREAD

**Issue by songlin1994** [JetBrains/teamcity-documentation#27]
那么  自动 生成  一些  y d m参数
如果加入 转义符  \ 
那么 效果 是这样
![image](https://user-images.githubusercontent.com/33373254/69520376-7b387f80-0f97-11ea-9071-2e5b44c478ca.png)
![image](https://user-images.githubusercontent.com/33373254/69520399-93100380-0f97-11ea-8312-4f844e76126d.png)

**Comment by songlin1994** [comment]
Then automatically generate some y d m parameters
If you add the escape character \
Then the effect is like this

**Comment by mkjetbrains** [comment]
Hi! Sorry for the delayed response. Is this issue still relevant for you?
If you wanted to use percent symbols without them being treated as a parameter reference, we suggest that you use two percent symbols one by one: the first one will be used as an escape character, and only the second one will be passed. For example, if you want to pass `%Y%m%d%H%M%S`, use `%%Y%%m%%d%%H%%M%%S`.
