### ISSUE TITLE
does the pattern matching work in clean-up keep rules for branchech and tags?

### ISSUE THREAD

**Issue by travnick** [JetBrains/teamcity-documentation#39]
I'm Asking since the information is missing - and it would be great to have it explained in documentation.

**Comment by mkjetbrains** [comment]
Hi!
When editing a keep rule, you can use a regular TeamCity [branch filter](https://www.jetbrains.com/help/teamcity/branch-filter.html) for branch pattern matching. As for tags, it is expected that exact tag names are entered.
We will try to clarify this in the documentation, thank you.
