### ISSUE TITLE
I want to automatically download artifacts of a project daily in teamicty

### ISSUE THREAD

**Issue by manikumary** [JetBrains/teamcity-documentation#4]
From Teamcity dashboard . Assume project is configured and daily artifacts are available daily. I want to download them daily automatically .What are possible ways to do that ?

**Comment by dmitry-treskunov** [comment]
Hi, the best place for such questions is our public forum https://teamcity-support.jetbrains.com/hc/en-us/community/topics

As for the question itself, you can download artifacts using [Rest API ](https://www.jetbrains.com/help/teamcity/2019.1/rest-api.html#RESTAPI-BuildArtifacts)
