### ISSUE TITLE
Clarify configuration for internal consumption of TeamCity NuGet feeds

### ISSUE THREAD

**Issue by pjt33** [JetBrains/teamcity-documentation#62]
https://www.jetbrains.com/help/teamcity/using-teamcity-as-nuget-feed.html says

> You can use TeamCity NuGet feeds to restore packages in your builds: when the NuGet Installer or NuGet Publish build step is used, TeamCity will use the credentials provider to automatically authenticate requests to the private TeamCity NuGet feeds.

It would be useful to say that the alternative, if you have a VS / MSBuild build step with `Restore` among its targets, is to add a "NuGet feed credentials" build feature. (Even more helpful would be to automatically use the credentials provider with VS / MSBuild, but that's a feature request which belongs in a different issue tracker).

**Comment by mkjetbrains** [comment]
Hi!
Thanks for noting this, it indeed makes sense to mention all the related build runners in this paragraph.
However, could you please describe your case? If you authenticate in private **TeamCity** feeds via any step (MSBuild, VS, .NET), TeamCity runs internal credential provider automatically, as with NuGet Installer or NuGet Publish. If you authenticate in an external private feed, this case requires adding the NuGet Feed Credentials feature for any of the mentioned runners. The behavior should be consistent. If you have noticed any issues with it, please let us know about it either here or via our [issue tracker](https://youtrack.jetbrains.com/issues/TW).

**Comment by mkjetbrains** [comment]
Hello again. Supposedly, we can close this issue for now? I've mentioned the missing runners in the respective paragraph, thanks to your comment. As to the expected behavior, I would still encourage you to describe your case either in the related issue in the NuGet Support repo, or in our tracker.
Thank you.

**Comment by pjt33** [comment]
Sorry, I've been busy trying to get a release together for a different project. I've added more details to the other issue on Github.
