### ISSUE TITLE
Hi, I want help : how do build this project?

### ISSUE THREAD

**Issue by mrp8ge8** [JetBrains/teamcity-documentation#92]
how do build this project ,to my local off line website。
like  https://www.jetbrains.com/help/teamcity/2020.1/teamcity-documentation.html

**Comment by mkjetbrains** [comment]
Hi! Sorry for the delayed response.
If I understood correctly, you want to build the TeamCity documentation locally on your machine? I'm afraid this won't be possible as it is built using the internal JetBrains documentation engine. You can, however, clone this repo to your desktop and use any convenient markdown viewer to compose a documentation tree locally and browse through pages. Please note that our docs use a mix syntax of markdown and HTML, so some tags might not be rendered properly in external software.
If your question was about something else, please let me know.

**Comment by mrp8ge8** [comment]
Thanks. Your understanding is correct.

I use the other way, download as CHM
